# Generated by Django 4.1.5 on 2023-01-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='html_css',
            new_name='fantastic_beats_books',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='java_script',
            new_name='harry_potter_books',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='field_name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='field_name',
            new_name='slug',
        ),
    ]
