# Generated by Django 4.1.5 on 2023-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_rename_html_css_book_fantastic_beats_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
            ],
        ),
    ]
