# Generated by Django 4.1.5 on 2023-01-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0004_rename_book_name_search_name_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='book_file'),
        ),
    ]
